### ISSUE TITLE
[feature] A CommandSender interface like in bukkit

### ISSUE THREAD

**Issue by DSeeLP** [KelpFramework/kelp#58]
**Is your feature request related to a problem? Please describe.**
You currently multiple util methods for the same thing because there is no unified CommandSender, where you for example send Messages to.

**Describe the solution you'd like**
A interface that is implemented by KelpConsoleSender and KelpPlayer which has for example hasPermission and sendMessage methods.

**Comment by PXAV** [comment]
Kelp already has a feature that tries to make this unnecessary. When creating a command you can enable that the `onCommand` method with a `KelpPlayer` is delegated to the console sender message automatically and you can use the method with the console sender for both cases, which looks like this:

```java
@CreateCommand(name = "test", executorType = ExecutorType.PLAYER_AND_CONSOLE)
public class TestCommand extends KelpCommand {

  @Override
  public void onCommandRegister() {
    delegatePlayerToConsole(true); // whenever the player method would be called, it executes the console sender method
  }

  @Override
  public void onCommand(KelpConsoleSender consoleSender, String[] args) {
    System.out.println("You executed the command, " + consoleSender.getName() + "!");
  }
  
}

```

But you are right that permission checks are not possible this way. So maybe it would be good to create such an interface.

Or maybe there should be a method `KelpConsoleSender#getPlayer()` that returns a player if the console sender is a player or `null` if the command was executed by the console. This way you would be able to directly interact with the `KelpPlayer` class.

**Comment by DSeeLP** [comment]
I think at some point its planned to add some CommandSenders like the RemoteCommandSender. At this point i think for consumers its easier to use a single interface instead of multiple Command classes and hassle with methods like getPlayer or hasPermission.

**Comment by DSeeLP** [comment]
If this is accepted i would add it in the pr for my commandsystem

**Comment by PXAV** [comment]
Hmm yes, the command system really has only been created for single responsibility use. The delegation system works great if your command method only handles a single (sub-)command, but as soon as you want to include a complex handler there to avoid creating thousands of classes, the system breaks. 

So yeah you could integrate this interface in the new command system, but please don't delete the old system yet.

**Comment by DSeeLP** [comment]
Oh with Command classes i meant CommandSender classes. And in my pr I won't delete anything. I think this can be discussed in #59 so i will close this now.
