### ISSUE TITLE
[feature] Declarative Command System for Kotlin and Java Kelp Apps

### ISSUE THREAD

**Issue by DSeeLP** [KelpFramework/kelp#59]
**Is your feature request related to a problem? Please describe.**
Currently for complex commands you need to create lots of classes. My Command System uses a Brigadier like Builder.

**Describe the solution you'd like**
I can implement the logic for my system myself in Kelp and create a pull request for it.

**Additional context**
Here's the link to my system: https://github.com/DSeeLP/Kommon/tree/development/command

**Comment by PXAV** [comment]
That's a great idea. I have just looked a bit through Brigadier and KommonCommand and it's both really intuitive to understand. If you can, I would appreciate a pull request with the new command system. 

Will it also be able to manipulate existing commands that have not created by the current plugin like it is in Brigadier?

**Comment by DSeeLP** [comment]
Resolved in #60
