### ISSUE TITLE
[bugreport]: kelp shows wrong version

### ISSUE THREAD

**Issue by DSeeLP** [KelpFramework/kelp#63]
### Describe the bug
In the console kelp uses the version 0.3.3 instead of 0.3.4

### What do we have to do to reproduce this bug? 
1. Use Kelp 0.3.4
### What would you expect to happen?
It should show version 0.3.4 instead of 0.3.3
### Environment information
* Operating system: Linux Ubuntu 20.10
* Java-Version: 1.8
* Kelp-Core-Version: v.0.3.4
* Version-Implementation: 1.8

**Comment by PXAV** [comment]
Hi, there won't be an extra release to fix this issue for `0.3.4`, but I have added a `plugin.yml` with
```yml
version: ${project.version}
```
which automatically reads the maven version and should fix the problem for future updates.
